name: Update Playlist

on:
  push:
    paths:
      - channels.txt

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate Playlist
        run: python generate.py

      - name: Commit Playlist
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add combined_playlist.m3u

          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "Auto update playlist"
            git push
          fi
